//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.04 at 03:13:33 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://interstellar.discovery.com/web/soap/domain", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.discovery.interstellar.web.soap.domain;
